- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76

- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base
    vars:
      emea_jfrog: "emea var"
      nafta_jfrog: "nafta var"

- job:
    name: checklabel_emea
    run: playbooks/checklabel_emea.yaml
    parent: base

- job:
    name: checklabel_nafta
    run: playbooks/checklabel_nafta.yaml
    parent: base


- project:
    checklabel_emea:
      jobs:
       - checklabel_emea:
           nodeset: emea-node
    checklabel_nafta:
      jobs:
       - checklabel_nafta:
           nodeset: nafta-node
    check_emea:
      jobs:
       - demomavenbuildjob:
           nodeset: emea-node
    check_nafta:
      jobs:
       - demomavenbuildjob:
           nodeset: nafta-node
