- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76

- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base
#    vars:
#      emea_jfrog: "http://172.31.27.120:9081"
#      nafta_jfrog: "http://172.31.20.75:9082"

- job:
    name: checklabel_emea
    run: playbooks/checklabel_emea.yaml
    parent: base

- job:
    name: checklabel_nafta
    run: playbooks/checklabel_nafta.yaml
    parent: base


- project:
    name: testproject
    vars:
      myname: "juhi"
    checklabel_emea:
      jobs:
       - checklabel_emea:
           nodeset: emea-node
    checklabel_nafta:
      jobs:
       - checklabel_nafta:
           nodeset: nafta-node
    check_emea:
      jobs:
        - demomavenbuildjob:
 #           vars:
 #             emea_jfrog: "http://172.31.27.120:9081"
            nodeset: emea-node
    check_nafta:
      jobs:
        - demomavenbuildjob:
#            vars: 
#              nafta_jfrog: "http://172.31.20.75:9082"
            nodeset: nafta-node
