- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76

- job:
    name: demomavenbuildjob
    run: playbooks/demomavenbuild.yaml
    parent: base

- job:
    name: checklabel_emea
    run: playbooks/checklabel_emea.yaml
    parent: base

- job:
    name: checklabel_nafta
    run: playbooks/checklabel_nafta.yaml
    parent: base


- project:
    checklabel_emea:
      jobs:
       - checklabel_emea:
           nodeset: emea-node
    checklabel_nafta:
      jobs:
       - checklabel_nafta:
           nodeset: nafta-node
    check_emea:
      jobs:
       - demomavenbuildjob:
           vars:
             emea_jfrog: https://52.66.200.85:9081
           nodeset: emea-node
    check_nafta:
      jobs:
       - demomavenbuildjob:
           vars:
             nafta_jfrog: https://35.154.28.215:9082
           nodeset: nafta-node
